package JobQueue;

import java.util.ArrayList;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dimach
 */
public class JobQueue extends javax.swing.JFrame
{
    /**
     * Creates new form JobQueue
     */
    public JobQueue()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        class2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        class3 = new javax.swing.JTextField();
        class4 = new javax.swing.JTextField();
        class5 = new javax.swing.JTextField();
        class1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        toggle1 = new javax.swing.JToggleButton();
        toggle2 = new javax.swing.JToggleButton();
        toggle3 = new javax.swing.JToggleButton();
        toggle4 = new javax.swing.JToggleButton();
        toggle5 = new javax.swing.JToggleButton();
        loadSystem = new javax.swing.JButton();
        stopSystem = new javax.swing.JButton();
        job5 = new javax.swing.JTextField();
        job4 = new javax.swing.JTextField();
        job3 = new javax.swing.JTextField();
        job2 = new javax.swing.JTextField();
        job1 = new javax.swing.JTextField();
        status5 = new javax.swing.JLabel();
        status4 = new javax.swing.JLabel();
        status3 = new javax.swing.JLabel();
        status2 = new javax.swing.JLabel();
        status1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputQueue = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputQueue = new javax.swing.JList();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Job Queue");
        setResizable(false);

        class2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        class2.setText("AB");

        jLabel1.setText("Init 1");

        jLabel2.setText("Init 2");

        jLabel3.setText("Init 3");

        jLabel4.setText("Init 4");

        jLabel5.setText("Init 5");

        class3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        class3.setText("X");

        class4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        class4.setText("Y");

        class5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        class5.setText("Z");
        class5.setToolTipText("");

        class1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        class1.setText("A");

        jLabel6.setText("Class");

        jLabel7.setText("Job");

        jLabel8.setText("Status");

        toggle1.setText("Start");
        toggle1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                toggle1ActionPerformed(evt);
            }
        });

        toggle2.setText("Start");
        toggle2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                toggle2ActionPerformed(evt);
            }
        });

        toggle3.setText("Start");
        toggle3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                toggle3ActionPerformed(evt);
            }
        });

        toggle4.setText("Start");
        toggle4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                toggle4ActionPerformed(evt);
            }
        });

        toggle5.setText("Start");
        toggle5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                toggle5ActionPerformed(evt);
            }
        });

        loadSystem.setText("Load System");
        loadSystem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                loadSystemActionPerformed(evt);
            }
        });

        stopSystem.setText("Stop System");
        stopSystem.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                stopSystemActionPerformed(evt);
            }
        });

        job5.setEditable(false);
        job5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        job4.setEditable(false);
        job4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        job3.setEditable(false);
        job3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        job2.setEditable(false);
        job2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        job1.setEditable(false);
        job1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        status5.setText("Stopped");

        status4.setText("Stopped");

        status3.setText("Stopped");

        status2.setText("Stopped");

        status1.setText("Stopped");

        jScrollPane1.setViewportView(inputQueue);

        jScrollPane2.setViewportView(outputQueue);

        jLabel14.setText("Input Queue");

        jLabel15.setText("Output Queue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel1)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel2)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel3)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel4)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(class1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(class2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(job1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(job2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(status1)
                                                .addGap(23, 23, 23)
                                                .addComponent(status2)
                                                .addGap(8, 8, 8))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel14))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(toggle1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(toggle2)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(job3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(job4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(job5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(class3)
                                                .addComponent(toggle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(status3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(class4)
                                                    .addComponent(toggle4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(class5)
                                                    .addComponent(toggle5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(status4)
                                                .addGap(23, 23, 23)
                                                .addComponent(status5)
                                                .addGap(8, 8, 8))
                                            .addComponent(jLabel15))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(loadSystem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(stopSystem))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(class2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(class3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(class4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(class5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(class1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(job5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(job4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(job3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(job2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(job1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(status5)
                    .addComponent(status4)
                    .addComponent(status2)
                    .addComponent(status1)
                    .addComponent(status3))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toggle1)
                    .addComponent(toggle2)
                    .addComponent(toggle3)
                    .addComponent(toggle4)
                    .addComponent(toggle5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadSystem)
                    .addComponent(stopSystem))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    Initiator init = new Initiator();
    Job job = new Job();
    ArrayList<Job> arrayJob = new ArrayList<>();
    
    private void toggle1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_toggle1ActionPerformed
    {//GEN-HEADEREND:event_toggle1ActionPerformed
        if (toggle1.getText().equals("Start"))
        {
            toggle1.setText("Stop");
            init.changeClass(class1.getText(), status1.getText());
            job.jobNumber++;
            job.jobName = "Job " + job.jobNumber;
            job1.setText(job.jobName);
            status1.setText(init.initStatus);
        }
        else
        {
            init.changeClass(class1.getText(), status1.getText());
            status1.setText(init.initStatus);
            job1.setText("");
            toggle1.setText("Start");
        }
    }//GEN-LAST:event_toggle1ActionPerformed

    private void toggle2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_toggle2ActionPerformed
    {//GEN-HEADEREND:event_toggle2ActionPerformed
        if (toggle2.getText().equals("Start"))
        {
            toggle2.setText("Stop");
            init.changeClass(class2.getText(), status2.getText());
            job.jobNumber++;
            job.jobName = "Job " + job.jobNumber;
            job2.setText(job.jobName);
            status2.setText(init.initStatus);
        }
        else
        {
            init.changeClass(class2.getText(), status2.getText());
            status2.setText(init.initStatus);
            job2.setText("");
            toggle2.setText("Start");
        }
    }//GEN-LAST:event_toggle2ActionPerformed

    private void loadSystemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_loadSystemActionPerformed
    {//GEN-HEADEREND:event_loadSystemActionPerformed
        //arrayJob.add();
    }//GEN-LAST:event_loadSystemActionPerformed

    private void stopSystemActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_stopSystemActionPerformed
    {//GEN-HEADEREND:event_stopSystemActionPerformed
        // Stop all initiators and drain
    }//GEN-LAST:event_stopSystemActionPerformed

    private void toggle3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_toggle3ActionPerformed
    {//GEN-HEADEREND:event_toggle3ActionPerformed
        if (toggle3.getText().equals("Start"))
        {
            toggle3.setText("Stop");
            init.changeClass(class3.getText(), status3.getText());
            job.jobNumber++;
            job.jobName = "Job " + job.jobNumber;
            job3.setText(job.jobName);
            status3.setText(init.initStatus);
        }
        else
        {
            init.changeClass(class3.getText(), status3.getText());
            status3.setText(init.initStatus);
            job3.setText("");
            toggle3.setText("Start");
        }
    }//GEN-LAST:event_toggle3ActionPerformed

    private void toggle4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_toggle4ActionPerformed
    {//GEN-HEADEREND:event_toggle4ActionPerformed
        if (toggle4.getText().equals("Start"))
        {
            toggle4.setText("Stop");
            init.changeClass(class4.getText(), status4.getText());
            job.jobNumber++;
            job.jobName = "Job " + job.jobNumber;
            job4.setText(job.jobName);
            status4.setText(init.initStatus);
        }
        else
        {
            init.changeClass(class4.getText(), status4.getText());
            status4.setText(init.initStatus);
            job4.setText("");
            toggle4.setText("Start");
        }
    }//GEN-LAST:event_toggle4ActionPerformed

    private void toggle5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_toggle5ActionPerformed
    {//GEN-HEADEREND:event_toggle5ActionPerformed
        if (toggle5.getText().equals("Start"))
        {
            toggle5.setText("Stop");
            init.changeClass(class5.getText(), status5.getText());
            job.jobNumber++;
            job.jobName = "Job " + job.jobNumber;
            job5.setText(job.jobName);
            status5.setText(init.initStatus);
        }
        else
        {
            init.changeClass(class5.getText(), status5.getText());
            status5.setText(init.initStatus);
            job5.setText("");
            toggle5.setText("Start");
        }
    }//GEN-LAST:event_toggle5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JobQueue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JobQueue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JobQueue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JobQueue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new JobQueue().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField class1;
    private javax.swing.JTextField class2;
    private javax.swing.JTextField class3;
    private javax.swing.JTextField class4;
    private javax.swing.JTextField class5;
    private javax.swing.JList inputQueue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField job1;
    private javax.swing.JTextField job2;
    private javax.swing.JTextField job3;
    private javax.swing.JTextField job4;
    private javax.swing.JTextField job5;
    private javax.swing.JButton loadSystem;
    private javax.swing.JList outputQueue;
    private javax.swing.JLabel status1;
    private javax.swing.JLabel status2;
    private javax.swing.JLabel status3;
    private javax.swing.JLabel status4;
    private javax.swing.JLabel status5;
    private javax.swing.JButton stopSystem;
    private javax.swing.JToggleButton toggle1;
    private javax.swing.JToggleButton toggle2;
    private javax.swing.JToggleButton toggle3;
    private javax.swing.JToggleButton toggle4;
    private javax.swing.JToggleButton toggle5;
    // End of variables declaration//GEN-END:variables
}
